/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'limsim' at '14/10/16 21:10' with Gradle 3.1
 *
 * @author limsim, @date 14/10/16 21:10
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
